---
title: "GGPlot Project"
author: "Olivia & Yulia"
date: '2022-11-22'
output: html_document
---

```{r setup, include=FALSE }
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(tidyverse)
library(kableExtra)
library(ggthemes)
library(sjmisc)
library(raster)
library(stringr)

setwd("C:/Users/zales/Documents/BSB3/R/Margeurit David/Final Project/")

report2019 <- read.csv("HappinessReport/2019.csv", header = TRUE, sep = ",")
report2018 <- read.csv("HappinessReport/2018.csv", header = TRUE, sep = ",")
report2017 <- read.csv("HappinessReport/2017.csv", header = TRUE, sep = ",")
report2016 <- read.csv("HappinessReport/2016.csv", header = TRUE, sep = ",")
report2015 <- read.csv("HappinessReport/2015.csv", header = TRUE, sep = ",")
report2019$Year <- 2019
report2018$Year <- 2018
report2017$Year <- 2017
report2016$Year <- 2016
report2015$Year <- 2015


selectColumns <- c("Happiness.Rank", "Country",'Happiness.Score', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Trust..Government.Corruption.', 'Year')

columns <- c('Overall.rank', 'Country.or.region','Score','GDP.per.capita','Social.support','Healthy.life.expectancy','Freedom.to.make.life.choices','Generosity','Perceptions.of.corruption', 'Year')


report2015 <- report2015[,selectColumns]
report2016 <- report2016[,selectColumns]
report2017 <- report2017[,selectColumns]
colnames(report2015) <- columns
colnames(report2016) <- columns
colnames(report2017) <- columns


reportTotal <- rbind(report2016, report2015, report2017, report2018, report2019)

reportTotal <- merge(x=reportTotal,y=ccodes()[,c('NAME','UNREGION1','continent')], 
      by.x=c("Country.or.region"), 
      by.y=c("NAME"),
      all.x=TRUE)



# Update Country Names only for the map graph - reference with report2019a

report2019a <- report2019

report2019a[report2019a$Country.or.region=="United States", "Country.or.region"] <- "USA"
report2019a[report2019a$Country.or.region=="United Kingdom", "Country.or.region"] <- "UK"
report2019a[report2019a$Country.or.region=="Congo (Brazzaville)", "Country.or.region"] <- "Democratic Republic of the Congo"
report2019[report2019a$Country.or.region=="Congo (Kinshasa)", "Country.or.region"] <- "Democratic Republic of the Congo"
report2019a



reportTotal[reportTotal$Country.or.region=="Congo (Brazzaville)", "Country.or.region"] <- "Democratic Republic of the Congo"
reportTotal[reportTotal$Country.or.region=="Congo (Kinshasa)", "Country.or.region"] <- "Democratic Republic of the Congo"
reportTotal[reportTotal$Country.or.region=="Ivory Coast", "Country.or.region"] <- "Côte d'Ivoire"
reportTotal[reportTotal$Country.or.region=="Palestinian Territories", "Country.or.region"] <- "Palestina"
reportTotal[reportTotal$Country.or.region=="Trinidad & Tobago", "Country.or.region"] <- "Trinidad and Tobago"

reportTotal[reportTotal$Country.or.region=="North Cyprus", "Country.or.region"] <- "Northern Cyprus"
reportTotal


```




# World Happiness Report {.tabset .tabset-fade}


## France


```{r echo=FALSE, message=FALSE, warning=FALSE}

france <- reportTotal[reportTotal$Country.or.region == "France",]


france <- filter(reportTotal, Country.or.region == "France")

g <- ggplot(france, aes(x = Year, y = Overall.rank)) + 
  geom_line() 


percentChange <- reportTotal[,4:9]

library(scales)
f1 <- france

for( i in 1:5){
  for(k in 2:9){
    f1[i,k] <- (as.numeric(as.character(france[i,k])) - as.numeric(as.character(france[5,k])))/ as.numeric(as.character(france[5,k]))
  }
}


g



```




```{r echo=FALSE, message=FALSE, warning=FALSE}
#load necessary libraries
library(ggplot2)
library(reshape2)


f <- f1[4:10]
f <- melt(f, id.vars = 'Year', variable.name= 'series')

f$value <- as.numeric(f$value)


ggplot(f, aes(Year, value)) +
  geom_line(aes(colour = series)) +
  geom_point(aes(colour = series)) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~series)

```



## Continent

trends by continent


```{r echo=FALSE, message=FALSE, warning=FALSE }

report2019 <- merge(x=report2019,y=ccodes()[,c('NAME','UNREGION1','continent')], 
      by.x=c("Country.or.region"), 
      by.y=c("NAME"),
      all.x=TRUE)

stats <- reportTotal %>% 
          group_by(continent, Year) %>% 
          summarize_all(mean)




ggplot(stats, aes(Year, Score, group_by(continent))) +
  geom_line(aes(colour = continent)) +
  geom_point(aes(colour = continent))

```

<h2> Change in Rank</h2>

```{r echo=FALSE, message=FALSE, warning=FALSE }

report <- merge(x = report2019, y = report2015, by = "Country.or.region", all = TRUE)

report["Change.in.Rank"] <- report[,"Overall.rank.x"] - report[,"Overall.rank.y"]

report <- report[order(report$Change.in.Rank),]
report <- na.omit(report)


ggplot(report[c(1:10, 135:145),], aes(x=reorder(Country.or.region, Change.in.Rank), y=Change.in.Rank)) + 
  geom_bar(stat='identity', aes(fill="Overall.rank.x"), width=.5)  +
  labs(title= "Change in rank from 2015 - 2019", subtitle="Showing highest/lowest changes") + 
  coord_flip()
  

myVar = "Madam Duck"

```


<h1>`r myVar`</h1>


#

